### ISSUE TITLE
[Feature Request] Build application in docker

### ISSUE THREAD

**Issue by sinamics** [teziovsky/vehicle-service-book#48]
Hi.
Greate app. 👍 
Would be nice to have this application in a docker container

**Comment by teziovsky** [comment]
Hey there!
Thanks! I'm currently in the process of refactoring the application to leverage the latest version of Next with RSC. I'll hold off on adding the Docker container until I've wrapped up the refactor. Excited to hear your recommendations!

**Comment by sinamics** [comment]
Sounds good, looking forward to the rebuilded version.
